version: 2
jobs:
  build:
    branches:
      ignore:
        - gh-pages

    docker:
      # a packaged system that has the instructions for creating a running container.
      - image: circleci/node

    # actions that need to be taken to perform your job
    steps:
      - restore_cache:
          keys:
            - source-v1- #one time, not every time!

      # checks out the source code for a job over SSH
      - checkout

      - save_cache:
          key: source-v1-1 # Sept 7, 2019
          paths:
            - ".git"

      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
            - yarn-packages

      - run:
          name: install dependencies
          command: |
            yarn install 
            yarn add percy

      - save_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - run:
          name: percy screenshots
          command: |
            gatsby build
            percy snapshot public
